name: "Custom JS Greeting Action"
description: "A simple GitHub Action that greets the user"
author: "Chibuzo Ekwue"
branding:
  icon: "smile"
  color: "blue"

inputs:
  name:
    description: "The name of the person to greet"
    required: false
    default: "World"
outputs:
  greeting:
    description: "The greeting message"
runs:
  using: "node20"
  main: "dist/index.js"
